# Generated by Django 5.2.6 on 2025-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
